//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMBusService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusServiceContext : DbContext
    {
        public BusServiceContext()
            : base("name=BusServiceContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bus> buses { get; set; }
        public DbSet<busRoute> busRoutes { get; set; }
        public DbSet<busStop> busStops { get; set; }
        public DbSet<driver> drivers { get; set; }
        public DbSet<routeSchedule> routeSchedules { get; set; }
        public DbSet<routeStop> routeStops { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<trip> trips { get; set; }
        public DbSet<tripStop> tripStops { get; set; }
    }
}
