//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMBusService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public trip()
        {
            this.tripStops = new HashSet<tripStop>();
        }
    
        public int tripId { get; set; }
        public int routeScheduleId { get; set; }
        public System.DateTime tripDate { get; set; }
        public int driverId { get; set; }
        public int busId { get; set; }
        public string comments { get; set; }
    
        public virtual bus bus { get; set; }
        public virtual driver driver { get; set; }
        public virtual routeSchedule routeSchedule { get; set; }
        public virtual ICollection<tripStop> tripStops { get; set; }
    }
}
